# Generated by Django 4.1.5 on 2023-07-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.IntegerField(max_length=200),
        ),
    ]
