# Generated by Django 4.2.6 on 2023-12-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_uservote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservote',
            name='voting',
        ),
        migrations.AddField(
            model_name='uservote',
            name='choice_text',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AddField(
            model_name='uservote',
            name='user',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
