# Generated by Django 4.2.6 on 2023-12-26 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_remove_uservote_voting_uservote_choice_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservote',
            name='choice_text',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
