# Generated by Django 4.2.6 on 2023-12-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_uservote_choice_text_alter_uservote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservote',
            name='choice_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.choice'),
        ),
    ]
